# name: App CI using reusable workflow

# on:
#   push:
#     branches: [ main ]
#   workflow_dispatch:

# jobs:
#   call-reusable-workflow:
#     uses: konka-cloud-devops-platform/cicd-platform/.github/workflows/demo.yaml@main
#     with:
#       runner_label: konka
